variable "resource_group_name" {
  description = "The name of the resource group."
  type        = string
}

variable "virtual_network_name" {
  description = "The name of the virtual network."
  type        = string
}

variable "location" {
  description = "The location/region of the resources."
  type        = string
}

variable "os_disk" {
  description = "The os disk configuration to use for the virtual machine."
  type = object({
    caching              = optional(string, "ReadOnly")
    storage_account_type = optional(string, "Standard_LRS")
    name = optional(string, null)
  })
  default = {}
  nullable = false
}

variable "identity" {
  description = "values for the identity to use for the virtual machine."
  type = object({
    type = string
    identity_ids = optional(list(string))
  })
  default = null
}

variable "image" {
  description = "values for the image to use for the virtual machine."
  type = object({
    plan_id     = string
    publisher_id = string
    product_id      = string
    version   = optional(string, "latest") 
  })
}

variable "network_interfaces" {
  description = "A map of network_interfaces to create."
  type = map(object({
    accelerated_networking_enabled = optional(bool)
    name                           = optional(string)
    primary_interface              = optional(string, false)
    private_ip_address             = optional(string)
    private_ip_address_allocation  = optional(string, "Dynamic")
    public_ip_creation_enabled     = optional(bool, false)
    public_ip_config = optional(object({
      name              = optional(string)
      allocation_method = optional(string, "Dynamic")
      sku               = optional(string)
      tags              = optional(map(string), {})
    }), {})
    subnet_config = object({
      name             = optional(string)
      address_prefixes = list(string)
      tags             = optional(map(string))
    })
  }))
  default  = {}
  nullable = false

  validation {
    condition     = length([for k, v in var.network_interfaces : v.primary_interface if v.primary_interface]) == 1
    error_message = "At least one and only one network interface can be marked as primary."
  }
}

variable "admin_username" {
  description = "The admin username for the virtual machine."
  type        = string
}

variable "admin_password" {
  description = "The admin password for the virtual machine."
  type        = string
}

variable "virtual_machine_name" {
  description = "The name of the virtual machine."
  type        = string
}

variable "vm_size" {
  description = "The size of the virtual machine."
  type        = string
}

variable "custom_data" {
  description = "The custom data to use for the virtual machine."
  type        = string
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}
