name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**/go.mod'

permissions:
  contents: write
  pull-requests: read

jobs:
  acc-tests:
    runs-on: ubuntu-latest
    environment:
      name: acctests
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: init
        run: |
          docker run --rm -v $(pwd):/src -w /src -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_CLIENT_SECRET  mcr.microsoft.com/azterraform:latest make generate
      - name: e2e test
        run: |
          sh scripts/run-e2e-test.sh
      - name: upload test version snapshots
        uses: actions/upload-artifact@v3
        with:
          name: TestRecord-${{ github.event.number }}
          retention-days: 60
          path: |
            examples/**/TestRecord.md.tmp
      - name: version-upgrade test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sh scripts/version-upgrade-test.sh
